[[chapter-rest]]
== The REST Architectural Style

This is a simple and very brief summary of the REST architectural style. REST
was first described, and coined as a term, by Roy Fielding in his dissertation
_Architectural Styles and the Design of Network-based Software Architectures_
which was published in 2000.

REST stands for *Representational State Transfer* and denotes a set of software
architectural constraints and principles that can be used to characterize
software systems and to design and implement software systems.

Fielding's dissertation was in many ways a formalization of the principles and
architectural constraints he had identified and invented as part of his work
with the HTTP protocol and the World Wide Web. In the dissertation Fielding
begins with defining concepts and a terminology for categorizing and reasoning
about software architectures. Each category of software architectures is called
an *achitectural style*.

These concepts and categories are then used by Fielding to reason about the
properties that emerge in systems with a certain software architecture. In
particular, the REST architectural style emphasizes emergant properties such as
scalability of component interactions, generality of interfaces, independent
deployment of components, and intermediary components to reduce interaction
latency, enforce security, and encapsulate legacy systems (from the abstract
of the dissertation).

The architectural constraints of REST are as follows. Each constraint is
exemplified by some HTTP features and practical examples.

 * **Client-server**. *Examples*: Web browsers and web servers.
 * **Stateless**. Every HTTP request-response is independent of other
   request-responses.
 * **Cache**. This means that we can partially or completely eliminate some
   interactions and data transfers, improving efficiency, scalability and
   in the end, user-perceived performance. *Examples*: HTTP headers for
   indicating if resource representations are cacheable or not, and HTTP
   proxies and cache software.
 * **Uniform interface**. REST is defined as having four interface
   constraints: **identification of resources**; **manipulation of resources
   through representations**; **self-descriptive messages**; and, **hypermedia
   as the engine of application state**, also known as HATEOAS. *Examples*:
   HTTP relies on URL:s for identifying resources, media types for
   representation of resources and a set of HTTP commands; GET, POST etc for
   manipulating them, HTTP headers for describing messages. HTTP allows for
   hyperlinks to be specified in headers and then there are media types that
   enable hyperlinks to be embedded in resource representations like HTML.
 * **Layered system**.  This means that in each client-server interaction, the
   client can completely ignore what the server needs to do respond to client
   requests. *Examples*: The server can be a client to other server systems.
   This can be used to improve system scalability by enabling load balancing,
   HTTP proxies and intermediaries or that a server via a gateway interface
   interacts with a completely different type of system.
 * **Code-on-demand**. Allowing executable code to be downloaded improves system
   extensibility but reduces visibility so this is an optional constraint.
   *Example*: JavaScript in browsers.

The core data elements of REST are:

 * Resources and Resource Identifiers. URI:s, URN:s and URL:s.
 * Representations. HTTP media types.

HTTP is an application protocol for distributed hypermedia systems and is
designed to enable the construction of REST-ful systems. It can however like
many technical protocols be used for many other purposes and the construction
of systems that have other architectural properties than REST. WS/SOAP uses HTTP
as a transport protocol, which is ... an idea. However if a system wishes to use
HTTP for its intended purpose and for building REST-ful systems and thus for
achieving the architectural properties of a REST-style system, it is important
to use HTTP as it was intended and pay close attention to the architectural
constraints of REST.
